### ISSUE TITLE
训练到第十轮时报错：IndexError: list index out of range

### ISSUE THREAD

**Issue by kunempire** [FishAndWasabi/YOLO-MS#11]
return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
09/04 19:35:45 - mmengine - INFO - Exp name: yoloms_syncbn_fast_8xb8-300e_coco_20230904_193458
09/04 19:35:53 - mmengine - INFO - Exp name: yoloms_syncbn_fast_8xb8-300e_coco_20230904_193458
09/04 19:36:00 - mmengine - INFO - Exp name: yoloms_syncbn_fast_8xb8-300e_coco_20230904_193458
09/04 19:36:07 - mmengine - INFO - Exp name: yoloms_syncbn_fast_8xb8-300e_coco_20230904_193458
09/04 19:36:13 - mmengine - INFO - Exp name: yoloms_syncbn_fast_8xb8-300e_coco_20230904_193458
09/04 19:36:21 - mmengine - INFO - Exp name: yoloms_syncbn_fast_8xb8-300e_coco_20230904_193458
09/04 19:36:27 - mmengine - INFO - Exp name: yoloms_syncbn_fast_8xb8-300e_coco_20230904_193458
09/04 19:36:34 - mmengine - INFO - Exp name: yoloms_syncbn_fast_8xb8-300e_coco_20230904_193458
09/04 19:36:41 - mmengine - INFO - Exp name: yoloms_syncbn_fast_8xb8-300e_coco_20230904_193458
09/04 19:36:48 - mmengine - INFO - Exp name: yoloms_syncbn_fast_8xb8-300e_coco_20230904_193458
09/04 19:36:48 - mmengine - INFO - Saving checkpoint at 10 epochs
Traceback (most recent call last):
  File "/home/sysu/program/python/terrorismFlag/YOLO-MS/tools/train.py", line 114, in <module>
    main()
  File "/home/sysu/program/python/terrorismFlag/YOLO-MS/tools/train.py", line 110, in main
    runner.train()
  File "/home/sysu/software/anaconda3/envs/pytorch2.0/lib/python3.10/site-packages/mmengine/runner/runner.py", line 1706, in train
    model = self.train_loop.run()  # type: ignore
  File "/home/sysu/software/anaconda3/envs/pytorch2.0/lib/python3.10/site-packages/mmengine/runner/loops.py", line 102, in run
    self.runner.val_loop.run()
  File "/home/sysu/software/anaconda3/envs/pytorch2.0/lib/python3.10/site-packages/mmengine/runner/loops.py", line 366, in run
    metrics = self.evaluator.evaluate(len(self.dataloader.dataset))
  File "/home/sysu/software/anaconda3/envs/pytorch2.0/lib/python3.10/site-packages/mmengine/evaluator/evaluator.py", line 79, in evaluate
    _results = metric.evaluate(size)
  File "/home/sysu/software/anaconda3/envs/pytorch2.0/lib/python3.10/site-packages/mmengine/evaluator/metric.py", line 115, in evaluate
    _metrics = self.compute_metrics(results)  # type: ignore
  File "/home/sysu/software/anaconda3/envs/pytorch2.0/lib/python3.10/site-packages/mmdet/evaluation/metrics/coco_metric.py", line 419, in compute_metrics
    result_files = self.results2json(preds, outfile_prefix)
  File "/home/sysu/software/anaconda3/envs/pytorch2.0/lib/python3.10/site-packages/mmdet/evaluation/metrics/coco_metric.py", line 239, in results2json
    data['category_id'] = self.cat_ids[label]
IndexError: list index out of range

**Comment by FishAndWasabi** [comment]
The error "IndexError: list index out of range"  may occur due to incorrect label information. MS COCO has a default class number of 80. To resolve this issue, please update the config file according to the tutorial (https://mmyolo.readthedocs.io/en/latest/recommended_topics/labeling_to_deployment_tutorials.html#prepare-custom-dataset).

![image](https://github.com/FishAndWasabi/YOLO-MS/assets/45028025/1ea73b87-b1a2-4fa4-9a62-0c1d109a6489) 

We hope this helps. Thanks for your interest in our work!
  
Best Wishes! 😊
