### ISSUE TITLE
Train my own dataset: ValueError: class `YOLOv5CocoDataset`

### ISSUE THREAD

**Issue by Belinda-great** [FishAndWasabi/YOLO-MS#13]
HI Thank you for great work!
When I train my own dataset, there some error: 
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/opt/conda/lib/python3.8/site-packages/mmengine/runner/loops.py", line 44, in __init__
    super().__init__(runner, dataloader)
  File "/opt/conda/lib/python3.8/site-packages/mmengine/runner/base_loop.py", line 26, in __init__
    self.dataloader = runner.build_dataloader(
  File "/opt/conda/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1346, in build_dataloader
    dataset = DATASETS.build(dataset_cfg)
  File "/opt/conda/lib/python3.8/site-packages/mmengine/registry/registry.py", line 545, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/opt/conda/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 135, in build_from_cfg
    raise type(e)(
ValueError: class `YOLOv5CocoDataset` in mmyolo/datasets/yolov5_coco.py: need at least one array to concatenate

I modify the classes_num and name_clasess.
My config as flow:
[yoloms-xs_syncbn_fast_8xb8-300e_coco.txt](https://github.com/FishAndWasabi/YOLO-MS/files/12615237/yoloms-xs_syncbn_fast_8xb8-300e_coco.txt)

**Comment by FishAndWasabi** [comment]
Sorry for the delay.

We retested the program and did not get a similar error.
We think you may add `metainfo` into `dataset`  dict of the config.

![image](https://github.com/FishAndWasabi/YOLO-MS/assets/45028025/00878a31-c8ed-4cd4-8af9-b1256f7eb3ff)


We hope this helps. Thanks for your interest in our work!

Best Wishes! 😊
