### ISSUE TITLE
KeyError: 'YOLOMS is not in the mmyolo::model registry. 

### ISSUE THREAD

**Issue by xiawuhen** [FishAndWasabi/YOLO-MS#15]
python tools/train.py configs/yoloms/yoloms-xs_syncbn_fast_8xb8-300e_coco.py
运行时报错：
Traceback (most recent call last):
  File "tools/train.py", line 123, in <module>
    main()
  File "tools/train.py", line 112, in main
    runner = Runner.from_cfg(cfg)
  File "D:\anaconda\envs\mmyolo_ms\lib\site-packages\mmengine\runner\runner.py", line 445, in from_cfg
    runner = cls(
  File "D:\anaconda\envs\mmyolo_ms\lib\site-packages\mmengine\runner\runner.py", line 412, in __init__
    self.model = self.build_model(model)
  File "D:\anaconda\envs\mmyolo_ms\lib\site-packages\mmengine\runner\runner.py", line 819, in build_model
    model = MODELS.build(model)
  File "D:\anaconda\envs\mmyolo_ms\lib\site-packages\mmengine\registry\registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "D:\anaconda\envs\mmyolo_ms\lib\site-packages\mmengine\registry\build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "D:\anaconda\envs\mmyolo_ms\lib\site-packages\mmengine\registry\build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "d:\mmyolo\mmyolo\models\detectors\yolo_detector.py", line 41, in __init__
    super().__init__(
  File "D:\anaconda\envs\mmyolo_ms\lib\site-packages\mmdet\models\detectors\single_stage.py", line 30, in __init__
    self.backbone = MODELS.build(backbone)
  File "D:\anaconda\envs\mmyolo_ms\lib\site-packages\mmengine\registry\registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "D:\anaconda\envs\mmyolo_ms\lib\site-packages\mmengine\registry\build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "D:\anaconda\envs\mmyolo_ms\lib\site-packages\mmengine\registry\build_functions.py", line 100, in build_from_cfg
    raise KeyError(
KeyError: 'YOLOMS is not in the mmyolo::model registry. Please check whether the value of `YOLOMS` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/e
n/latest/advanced_tutorials/config.html#import-the-custom-module'

**Comment by FishAndWasabi** [comment]
该问题可能由于没有安装YOLOMS库导致。具体可以在目录下执行`pip install -v -e .`重新进行安装。具体细节可以参考install.md(https://github.com/FishAndWasabi/YOLO-MS/blob/main/docs/install.md)。

感谢您对我们工作的关注！

Best Wishes! 😊
