### ISSUE TITLE
TypeError: yolov5_collate() got an unexpected keyword argument '_scope_'

### ISSUE THREAD

**Issue by CcccccaptionOvO** [FishAndWasabi/YOLO-MS#8]
Traceback (most recent call last):
  File "tools/train.py", line 114, in <module>
    main()
  File "tools/train.py", line 110, in main
    runner.train()
  File "/data/.conda/envs/YOLO-MS/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1706, in train
    model = self.train_loop.run()  # type: ignore
  File "/data/.conda/envs/YOLO-MS/lib/python3.8/site-packages/mmengine/runner/loops.py", line 96, in run
    self.run_epoch()
  File "/data/.conda/envs/YOLO-MS/lib/python3.8/site-packages/mmengine/runner/loops.py", line 111, in run_epoch
    for idx, data_batch in enumerate(self.dataloader):
  File "/data/.conda/envs/YOLO-MS/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/data/.conda/envs/YOLO-MS/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1376, in _next_data
    return self._process_data(data)
  File "/data/.conda/envs/YOLO-MS/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1402, in _process_data
    data.reraise()
  File "/data/.conda/envs/YOLO-MS/lib/python3.8/site-packages/torch/_utils.py", line 461, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/data/.conda/envs/YOLO-MS/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/data/.conda/envs/YOLO-MS/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    return self.collate_fn(data)
TypeError: yolov5_collate() got an unexpected keyword argument '_scope_'

**Comment by CcccccaptionOvO** [comment]
我在

**Comment by CcccccaptionOvO** [comment]
**我在'mmyolo::rtmdet/rtmdet_l_syncbn_fast_8xb32-300e_coco.py'文件中按照以下步骤修改了dataloader，然后出现了一些新的问题**
train_dataloader = dict(
    ...
    collate_fn=dict(_delete_=True, type='yolov5_collate'),
    sampler=dict(_delete_=True, type='DefaultSampler', shuffle=True),
    ...
)

val_dataloader = dict(
    ...
    sampler=dict(_delete_=True, type='DefaultSampler', shuffle=True),
    ...
)

test_dataloader = val_dataloader
![image](https://github.com/FishAndWasabi/YOLO-MS/assets/98657929/e2f29149-2205-4608-8791-d4cdc19edbaa)

**Comment by FishAndWasabi** [comment]
您好，不需要在mmyolo::rtmdet/rtmdet_l_syncbn_fast_8xb32-300e_coco.py进行修改。请在您所使用的config文件里进行修改。

感谢您对我们工作的关注！

Best Wishes! 😊

**Comment by CcccccaptionOvO** [comment]
非常感谢！！！
